### ISSUE TITLE
VPC support

### ISSUE THREAD

**Issue by momonga-ml** [philschmid/terraform-aws-sagemaker-huggingface#12]
Add support for VPCs inside the module so that traffic will be encrypted in transit.
VPC would be parameters at the module layer to input VPC info.
The module would then use that to standup an endpoint inside the VPC.

We are happy to contribute and PR for this.

**Comment by philschmid** [comment]
Hello @momonga-ml, 

Great idea! If you have time to work on that a PR is more than welcome! A test/validation we have to then add is that if VPC only will work with "model_artifcats" and not with "hub" deployments since with the hub deployment the model will be loaded on the fly

**Comment by momonga-ml** [comment]
Okay, we will keep that in mind regarding Hub. We are going to start working on it this week. Will provide an update here later on.

**Comment by momonga-ml** [comment]
Hi Phil, looks like we ended up going a different direction on this one. I will reopen and PR if it comes back.
